### ISSUE TITLE
LocationManager receives no updates on Android S (with approximate location)

### ISSUE THREAD

**Issue by necavit** [fpearsonEsri/Android12LocationManagerIssue#1]
Hi @fpearson1111 

I've been reading your bug report at the Android issue tracker regarding the LocationManager not providing any location updates when only approximate location is granted to the app:

https://issuetracker.google.com/issues/203772229

Despite it should be fixed (should have been fixed a long time ago), I am currently facing the exact same incorrect behavior.

We cannot get any updates from LocationManager, whether we request them through the network or GPS providers... and regardless of the API we try (the native, non-deprecated methods of LocationManager or the LocationManagerCompat library).

Did you ever see this problem solved?

Might I be stumbling upon a faulty S build? Both in the emulator and in the device?

Anyway, thanks a lot in advance!

David Martínez
Android lead engineer at Wikiloc Outdoor

**Comment by fpearson1111** [comment]
Hi @necavit

I don't think I ever verified that this was fixed; I just took their comment at face value. I haven't heard about any problems since then. One thing to test is whether you get location updates when requesting course and fine location but with only course location granted, and when using the fused location provider -- as described in the report, the fused provider worked for me at the time. 

Other than that I don't think I can be of any more help, I would suggest asking in the report itself. Although if you have more questions I can try and answer them. Best of luck -- they don't make it easy :)

**Comment by necavit** [comment]
Hi @fpearson1111 

Thanks for the answer!

We've verified that, when requesting both coarse and fine location permissions, but the user granting coarse location only, the only way to get updates is using the Fused Location Provider. Other than that, it seems that the "platform-native" LocationManager is blocking all location requests when the only granted permission is coarse location.

For the sake of "documenting" our solution (for any interested party): so far, we've resorted to requiring the fine location permission at all times, so that all our location-bound features work correctly. We cannot rely on the fused provider, for a number of reasons (availability, bugs, accuracy, etc.), so we've had to drop support for approximate-only location grants.

We might request Google to review the fix in the original issue tracker post.

Thanks again for the answer and best of luck too!
